name: Deploy Solidity Contract

on:
  workflow_dispatch:
    inputs:
      loop_count:
        description: 'Number of times to run forge create'
        required: true
        default: '1'
        type: number

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc
          foundryup

      - name: Compile Contract
        run: forge compile

      - name: Deploy Contract Multiple Times
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          for i in $(seq 1 ${{ github.event.inputs.loop_count }}); do
            echo "Deployment $i..."
            forge create --private-key $PRIVATE_KEY src/Counter.sol:Counter --gas-price 100000000000 --gas-limit 95000 --broadcast | tee -a deployment.log
          done

      - name: Output Deployed Addresses
        run: cat deployment.log
